exclude: [".rvmrc", ".rbenv-version", "README.md", "changelog.md"]
markdown: kramdown
highlighter: rouge
permalink: pretty
collections:
  pages:
    output: true
    permalink: /:path/
name: Outlanders Trial site
  theme: jekyll-theme-minimal
  title: Outlanders homepage
  
